name: Build YouTube Music

on:
  push:
    branches: [ master ]
  pull_request:

env:
  NODE_VERSION: "22.x"

jobs:
  build:
    name: Build YouTube Music
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Xvfb (Linux only)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run tests (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' pnpm test

      - name: Run tests (Windows)
        if: startsWith(matrix.os, 'windows')
        run: pnpm test

      - name: Build and release on Linux
        if: startsWith(matrix.os, 'ubuntu') && (github.repository == 'srinivasaprasanna-vit/ytmd-clone' && github.event_name != 'pull_request')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install snapcraft --classic
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform/x86_64/24.08
          sudo flatpak install -y flathub org.freedesktop.Sdk/x86_64/24.08
          sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp/x86_64/24.08
          pnpm release:linux

      - name: Build and release on Windows
        if: startsWith(matrix.os, 'windows') && (github.repository == 'srinivasaprasanna-vit/ytmd-clone' && github.event_name != 'pull_request')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release:win

  release:
    runs-on: ubuntu-latest
    name: Release YouTube Music
    if: github.repository == 'srinivasaprasanna-vit/ytmd-clone' && github.ref == 'refs/heads/master'
    needs: build

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get version
        run: echo "VERSION_TAG=v$(node -pe "require('./package.json').version")" >> $GITHUB_ENV

      - name: Check if version already exists in tags
        run: |
          echo "VERSION_HASH=$(git rev-parse -q --verify 'refs/tags/${{ env.VERSION_TAG }}')" >> $GITHUB_ENV
          echo "CHANGELOG_ANCHOR=$(echo $VERSION_TAG | sed -e 's/\.//g')" >> $GITHUB_ENV

      # Add your desired release and changelog steps here, updating repo references if needed.
